(function(){const menu=document.querySelector('.menu');if(menu){menu.addEventListener('click',()=>{const nav=document.querySelector('nav'),open=nav.dataset.open==='1';nav.dataset.open=open?'0':'1';nav.style.display=open?'none':'flex';nav.style.flexDirection='column';nav.style.position='absolute';nav.style.top='74px';nav.style.right='4%';nav.style.background='white';nav.style.padding='18px 24px';nav.style.border='1px solid #e8e1da';nav.style.borderRadius='14px';});}const purpose=document.getElementById('purpose'),budget=document.getElementById('budget'),search=document.getElementById('cafeSearch'),cards=[...document.querySelectorAll('.cafe-card')],count=document.getElementById('resultCount'),empty=document.getElementById('noResults');function filterCafes(){if(!cards.length)return;const a=purpose?.value||'all',b=budget?.value||'all',q=(search?.value||'').trim().toLowerCase();let shown=0;cards.forEach(card=>{const show=(a==='all'||card.dataset.purpose===a)&&(b==='all'||card.dataset.budget===b)&&(!q||card.dataset.name.includes(q));card.hidden=!show;if(show)shown++;});if(count)count.textContent=`${shown} ${shown===1?'cafe':'cafes'} match your filters`;if(empty)empty.hidden=shown!==0;}[purpose,budget,search].forEach(el=>el?.addEventListener(el?.tagName==='INPUT'?'input':'change',filterCafes));document.getElementById('resetFilters')?.addEventListener('click',()=>{if(purpose)purpose.value='all';if(budget)budget.value='all';if(search)search.value='';filterCafes();});document.querySelectorAll('.heart').forEach(btn=>btn.addEventListener('click',()=>{btn.classList.toggle('saved');btn.textContent=btn.classList.contains('saved')?'♥':'♡';}));filterCafes();const result=document.getElementById('choiceResult'),messages={study:'Try the Study / Work category — look for comfortable seating and a calm setup.',date:'Try the Date / Chill category — focus on ambience, seating and an easy evening plan.',friends:'Try the Friends category — look for shareable snacks and comfortable group seating.',snack:'Try the budget-friendly options — choose something quick and close to your route.'};document.querySelectorAll('.choice').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');if(result)result.textContent=messages[btn.dataset.choice];}));})();

(function(){
const modal=document.getElementById('modal'),content=document.getElementById('modalContent'),toast=document.getElementById('toast');
const cards=[...document.querySelectorAll('.cafe-card')],search=document.getElementById('cafeSearch'),budget=document.getElementById('budget'),type=document.getElementById('typeFilter'),count=document.getElementById('resultCount'),empty=document.getElementById('noResults');
function msg(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove('show'),2200)}
function filter(){if(!cards.length)return;const q=(search?.value||'').toLowerCase().trim(),b=budget?.value||'all',t=type?.value||'all';let n=0;cards.forEach(c=>{const ok=(t==='all'||c.dataset.type===t)&&(b==='all'||c.dataset.budget===b)&&(!q||c.dataset.name.includes(q));c.hidden=!ok;if(ok)n++});count.textContent=n+' '+(n===1?'place':'places')+' found';empty.hidden=n>0}
[search,budget,type].forEach(x=>x?.addEventListener(x===search?'input':'change',filter));
document.getElementById('resetFilters')?.addEventListener('click',()=>{search.value='';budget.value='all';type.value='all';filter()});
document.querySelectorAll('.heart').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('saved');b.textContent=b.classList.contains('saved')?'♥':'♡';msg(b.classList.contains('saved')?'Added to favourites':'Removed from favourites')}));
document.querySelectorAll('.view-menu').forEach(b=>b.addEventListener('click',()=>{const name=b.dataset.cafe,src=document.querySelector(`[data-menu="${CSS.escape(name)}"]`);content.innerHTML='<p class="eyebrow">MENU</p><h2>'+name+'</h2><p class="muted">Add items to build a sample order.</p>'+src.innerHTML+'<div class="callout" id="total"><strong>Selected items: 0 • Total: ₹0</strong></div>';let total=0,n=0;content.querySelectorAll('.add-item').forEach(x=>x.addEventListener('click',()=>{total+=Number(x.dataset.price);n++;x.textContent='Added ✓';content.querySelector('#total').innerHTML='<strong>Selected items: '+n+' • Total: ₹'+total+'</strong>';msg(x.dataset.name+' added')}));modal.hidden=false}));
document.querySelectorAll('.reserve').forEach(b=>b.addEventListener('click',()=>{const name=b.dataset.cafe;content.innerHTML='<p class="eyebrow">TABLE RESERVATION</p><h2>Reserve at '+name+'</h2><form class="reservation-form"><label>Your Name<input required placeholder="Enter your name"></label><label>Date<input required type="date"></label><label>Time<select required><option value="">Choose time</option><option>12:30 PM</option><option>1:30 PM</option><option>7:00 PM</option><option>8:30 PM</option></select></label><label>Guests<select><option>2</option><option>3</option><option>4</option><option>5+</option></select></label><button class="btn primary" type="submit">Confirm Reservation</button></form>';modal.hidden=false;content.querySelector('form').addEventListener('submit',e=>{e.preventDefault();modal.hidden=true;msg('Reservation request noted for '+name+' ✓')})}));
document.getElementById('closeModal')?.addEventListener('click',()=>modal.hidden=true);modal?.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true});filter();
})();
